#!/usr/bin/env python

from argparse import ArgumentParser

from comp import SRComp
from validation import validate

parser = ArgumentParser(description = "SR Competition State validator")
parser.add_argument("compstate", help = "Competition state git repository path")

args = parser.parse_args()

comp = SRComp(args.compstate)
error_count = validate(comp)

exit(error_count)
